name: Deploy

on:
  push:
    branches: [main]

jobs:


  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy in Amazon EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && sudo chown ${USER_NAME}:${USER_NAME} private_key && chmod 600 private_key
          pwd
          ls -l private_key
          ssh -o StrictHostKeyChecking=no -i private_key -vvv ${USER_NAME}@${HOSTNAME} "\
            cd /var/www/API_Realworld_Quest &&
            git fetch --all &&
            git reset --hard origin/main &&
            bundle install"
