name: Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Deploy in Amazon EC2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          pwd
          ls -l private_key
          ssh -o StrictHostKeyChecking=no -i private_key  ${USER_NAME}@${HOSTNAME} "\
            source ~/.bashrc &&
            cd /var/www/API_Realworld_Quest &&
            git fetch --all &&
            git reset --hard origin/main &&
            ~/.rbenv/shims/bundle install &&
            if [ -f tmp/pids/server.pid ]; then
              PID=$(cat tmp/pids/server.pid)
              echo "PID: $PID"
              if [ -n "$PID" ]; then
                kill -SIGTERM $PID || true
              fi
              rm -f tmp/pids/server.pid
            fi &&
            sudo systemctl stop nginx &&
            sudo systemctl start nginx &&
            screen -dm RAILS_ENV=production ~/.rbenv/shims/bundle exec pumactl start
            "
